#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

data = json.load(sys.stdin)

agent.set_env("TRAEFIK_HOST", data["host"])
agent.set_env("CALRS_MAIL_FROM", data.get("mail_from", ""))
agent.set_env("CALRS_ALLOW_PRIVATE_HOSTS", ",".join(data.get("allow_private_hosts", [])))
