#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

private_hosts = os.environ.get("CALRS_ALLOW_PRIVATE_HOSTS", "")

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "lets_encrypt": os.environ["TRAEFIK_LETS_ENCRYPT"] == "True",
    "host": os.environ["TRAEFIK_HOST"],
    "mail_from": os.environ.get("CALRS_MAIL_FROM", ""),
    "allow_private_hosts": private_hosts.split(",") if private_hosts else [],
    "admin_email": os.environ.get("CALRS_ADMIN_EMAIL", ""),
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
