#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent

config = {}

config["host"] = os.getenv("TRAEFIK_HOST", "")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = agent.get_route(os.environ['MODULE_ID']).get('lets_encrypt', False)
config["mail_from"] = os.getenv("CALRS_MAIL_FROM", "")
private_hosts = os.getenv("CALRS_ALLOW_PRIVATE_HOSTS", "")
config["allow_private_hosts"] = private_hosts.split(",") if private_hosts else []
# Empty tells the UI the administrator is still to be created
config["admin_email"] = os.getenv("CALRS_ADMIN_EMAIL", "")

json.dump(config, fp=sys.stdout)
